hours/views.py
from __future__ import absolute_import
from django import forms
from django.shortcuts import render
from django.http import HttpResponse
from django.core.cache import cache
from django.utils import timezone
from django.core.serializers.json import DjangoJSONEncoder

import os, hashlib, json
import requests
from collections import OrderedDict
from datetime import datetime
from dateutil.relativedelta import relativedelta
from dateutil.parser import parse as parse_date

from hours.vacation import working_days

Users = None # TODO: API
Hours = None # TODO: API

GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY', '')
GOOGLE_API_URL = 'https://www.googleapis.com/calendar/v3/calendars/{}/events'
# [(account, calendar)] # TODO: relate to Capacity Calendar
GOOGLE_HOLIDAY_CALENDARS = [('fi', 'en.finnish%23holiday%40group.v.calendar.google.com'),
                            ('ger', 'en.german%23holiday@group.v.calendar.google.com'),
                            ('uk', 'nhlu96v728ekb5cp8tprfhrnbg@group.calendar.google.com'),
                            ('swi', 'en.ch%23holiday%40group.v.calendar.google.com')]

EMPLOYEE_TYPES = [
'Permanent - full-time',
'Permanent - part-time',
'Subcontractor',
'Permanent - no working time',
'Permanent - hourly pay',
]

TILL = (
('yesterday','Yesterday'),
('today','Today'),
('eom','End of Month'),)

def dtnow():
    return timezone.now()

class BillingForm(forms.Form):
    TYPES = tuple((k,k) for k in EMPLOYEE_TYPES)
    MONTHS = tuple((str(k),str(k)) for k in range(1,4))
    def get_recent_months(self):
        now = datetime.now().replace(day=1)
        dts = []
        for k in range(6):
            dts.append(now)
            now = now - relativedelta(months=1)
        return dts
    def get_recent_months_tuple(self):
        def fmt(dt):
            return '%s-%s'%(dt.month,dt.year)
        return (('','--',),) + tuple((fmt(k),fmt(k),) for k in self.get_recent_months())
    months_total = forms.ChoiceField(choices=MONTHS)
    types = forms.MultipleChoiceField(choices=TYPES)
    till = forms.ChoiceField(choices=TILL)
    only_this_month = forms.ChoiceField(label='Report this month only', choices=(), required=False)
    exclude = forms.CharField(max_length=255, label='Comma separated list of employee usernames to exclude', required=False)

    def __init__(self, *args, **kwargs):
        self.base_fields['only_this_month'].choices = self.get_recent_months_tuple()
        super(BillingForm, self).__init__(*args, **kwargs)

def billing(request):
    duration = 3600
    initial = {
        'months_total': '1',
        'types': ['Permanent - full-time','Permanent - part-time','Permanent - no working time'],
        'till': 'today',
        'exclude': '',
        }
    form = BillingForm(request.POST or None, initial=initial)
    cleaned_data = form.data
    if request.POST:
        form.full_clean()
        cleaned_data = form.cleaned_data
    else:
        cleaned_data = form.initial

    formhash = hashlib.md5(unicode(cleaned_data)).hexdigest()
    key = '{}_{}'.format('billing', formhash)
    key_updated = '{}_updated'.format(key)
    result = cache.get(key)

    if result is None:
        cache.set(key, {}, duration)#poor-man's stampede protection
        only_this_month = cleaned_data.get('only_this_month')
        months = []
        if only_this_month:
            only_this_month = parse_date(only_this_month)
            only_this_month = only_this_month.replace(day=1)
            months = [only_this_month]

        result = find_missing_hour_markings(
                n=int(cleaned_data.get('months_total')),
                wanted_user_types=cleaned_data.get('types'),
                till=cleaned_data.get('till'),
                exclude_usernames=(cleaned_data.get('exclude') or '').split(','),
                only_this_month=only_this_month,
                months=months,
                )
        cache.set(key, result, duration)
        cache.set(key_updated, dtnow(), duration)

    # group hours by year, month
    for tribe, users in result.iteritems():
        for user_index, user in enumerate(users):
            fmt_days = {}
            for day in user[2]:
                fmt_days.setdefault(day.year, {})
                month_human = calendar.month_name[day.month]
                fmt_days[day.year].setdefault(month_human, [])
                fmt_days[day.year][month_human].append(day)
            result[tribe][user_index][2] = fmt_days

    updated = cache.get(key_updated) or dtnow()
    context = {
        'updated': int((dtnow()-updated).total_seconds()/60),
        'result': result,
        'update_interval': int(duration/60),
        'form': form,
    }
    return render(request, 'billing.html', context)

def find_missing_hour_markings(till, n=1, wanted_user_types=None, exclude_usernames=[], months=[], only_this_month=None):
    teams = OrderedDict()
    teams[''] = OrderedDict({'name': 'No Tribe', 'users': []})
    now = datetime.now().replace(day=1)

    def till_end_of_month(dt):
        last_day_of_month = calendar.monthrange(dt.year, dt.month)[1]
        return dt.replace(day=last_day_of_month)

    if till:
        if till == 'yesterday':
            till = (datetime.now() - relativedelta(days=1))
        if till == 'today':
            till = datetime.now()
        if till == 'eom':
            dt_cmp = datetime.now() if not only_this_month else only_this_month
            till = till_end_of_month(dt_cmp)
    else:
        till = (datetime.now() - relativedelta(days=1))

    if not months:
        months.append(now)
        st = now
        for k in range(1, n):
            st -= relativedelta(months=1)
            months.append(st)

    #for user in Users.objects.filter(active=True).order_by('username'):
    for user in []:
        if wanted_user_types and user.type not in wanted_user_types:
            continue
        if user.username in exclude_usernames:
            continue
        team = user.primary_team or ''
        total_missing_days = []
        if team and not teams.get(team):
            teams.setdefault(team, OrderedDict())
            teams[team].setdefault('name', team.name)
            teams[team].setdefault('users', [])
        for start in months:
            if only_this_month:
                if (start.month != only_this_month.month and start.year != only_this_month.year):
                    continue
                else:
                    end = till = till_end_of_month(start)
            else:
                if start.month == till.month and start.year == till.year:
                    end = till + relativedelta(days=1)
                else:
                    end = start + relativedelta(months=1)
            hours = Hours.objects.filter(user=user, day__gte=start, day__lte=end)
            hour_markings = [k.day for k in hours]
            missing_days = set(working_days(user, start, till=till)).difference(set(hour_markings))
            if missing_days:
                total_missing_days += missing_days
        formatted_missing_days = sorted(total_missing_days)
        teams[team]['users'].append([user, user.balance, formatted_missing_days])
    g = OrderedDict()
    for k in teams.keys():
        g.setdefault(teams[k]['name'], [])
        g[teams[k]['name']] = teams[k]['users']
    return g

def calendar_holidays():
    params = {'maxResults': 9999, 'orderBy': 'startTime', 'showHiddenInvitations': True, 'singleEvents': True,
              'timeMin': '{0}-01-01T00:00:00.000z'.format(datetime.now().year-1), 'key': GOOGLE_API_KEY}
    data = []
    for account_id, calendar in GOOGLE_HOLIDAY_CALENDARS:
        url = GOOGLE_API_URL.format(calendar)
        res = requests.get(url, params=params)
        for h in json.loads(res.text)['items']:
            t = dict(day=datetime.strptime(h['start']['date'], "%Y-%m-%d"),
                     name=h['summary'],
                     account_id=account_id,
                     calendar=calendar,)
            data.append(t)
    return data

def to_json(data, ensure_ascii=False):
    return json.dumps(data, encoding='utf-8', cls=DjangoJSONEncoder, ensure_ascii=ensure_ascii, separators=(',',':'))

def gcalholidays(request):
    return HttpResponse(to_json(calendar_holidays()), content_type='application/json')

hours/templates/billing.html
{% load bootstrap %}
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<link href="https://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

<style>
body {
font-family: Menlo, Monaco, Consolas, "Lucida Console", monospace;
padding: 10px;
}
ul
{
    list-style-type: none;
    margin: 0px;
    padding: 0px;
}
li {
    margin-top: 10px;
    
}
.user {
    font-weight: bold;
}
.balance {
    color: red;
    font-size: 12px;
}
.separator {
    color: #ccc;
}
.days {
    font-size: 13.5px;
}
.month {
    font-weight: bold;
}
.form-container {
    padding: 10px;
}
.form-group {
}

select#id_types {
    height: 100px;
}
.actions {
    clear: both;
    padding: 10px;
}
</style>

</head>
<body>

<h1>Missing hour reports</h1>

<div>
<p>
Last update {{updated}} minutes ago. Results cached for {{update_interval}} minutes.
</p>
<p>
Lists employees, and days missing hour markings for the past month(s).
</p>
</div>

<div class="form-container">
<form enctype="multipart/form-data" method="post" action="" role="form">
{%csrf_token%}
<div>
{{form|bootstrap_horizontal}}
</div>
<div class="actions">
<input type="submit" value="Query" class="btn btn-submit">
</div>
</form>
</div>

<div>
{% for tribe,users in result.items %}
    {% if users %}
    <h2>{{tribe|safe}}</h2>
    {% endif %}
    <ul>
    {% for user in users %}
        {% if user.2 %}
        <li>
            <span class="user">{{user.0.first_name}} {{user.0.last_name}} ({{user.0.username}})</span>
            <span class="balance"></span>
            <span class="separator">:</span>
            <span class="days">
            {% for year,months in user.2.items %}
                <span class="month">{{year}}:</span>
                {% for month,days in months.items %}
                    <span class="month">{{month}}:</span>
                    {% for day in days %}
                        {{day|date:'j'}}{% if not forloop.last %},{% endif %}
                    {% endfor %}
                {% endfor %}
            {% endfor %}
            </span>
        </li>
        {% endif %}
    {% endfor %}
    </ul>
{% endfor %}
</div>


</body>
</html>